---
- hosts: localhost
  become: true
  tasks:
    - name: "Installing apache server"
      ansible.builtin.apk:
        name: apache2
        state: present

    - name: "Copying the webpage"
      ansible.builtin.copy:
        src: apache/templates/index.html.j2
        dest: /tmp/index.html
        mode: preserve
        remote_src: yes
      register: x
    # - name: "Copying the webpage"
    #   ansible.builtin.copy:
    #     src: files/index.html
    #     dest: /var/www/html/index.html
    #   register: x
    # - name: "Starting service"
    #   ansible.builtin.service:
    #     name: httpd
    #     state: started
    #   when: x.changed